config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :groups, only: [:new, :create, :edit, :update, :show, :destroy, :index]
  resources :activities, only: [:new, :create, :edit, :update, :show, :destroy, :index]
  resources :scoreboards, only: [:index]
  root 'sessions#login'



  #routes to handle sessions:
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :activities
  default_scope -> { order(name: :asc) }

  validates :name, presence: true, uniqueness: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
    @icons_url = create_icons_array
  end

  def create
    @group = Group.new(group_params)
    @group.creator_id = session[:user_id]
    if @group.save
      redirect_to @group
    else
      flash[:danger] = 'Invalid group details'
      redirect_to new_group_path
    end
  end

  def show
    @group = Group.find(params[:id])
    @activities = @group.activities.all
  end

  # GET /group/1/edit
  def edit
    @group = Group.find(params[:id])
    @icons_url = create_icons_array
  end

  # PATCH/PUT /products/1
  def update
    group = Group.find(params[:id])
    respond_to do |format|
      if group.update(group_params)
        format.html { redirect_to group, notice: 'Group details were successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  def destroy
    group = Group.find(params[:id])
    group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully deleted from database.' }
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end

  def create_icons_array
    @icons_url = []
    @icons_url.append(['Choose an avatar', 'noicon.png'])
    @icons_url.append(%w[Anonymous noicon.png])
    @icons_url.append(['Basket ball', 'basketball-ball.png'])
    @icons_url.append(%w[Cycling bicycle.png])
    @icons_url.append(%w[Weightlifting dumbbell.png])
    @icons_url.append(%w[Skating figure-skating.png])
    @icons_url.append(%w[Fitness fitness.png])
    @icons_url.append(%w[Jogging jogging.png])
    @icons_url.append(['Martial arts', 'kimono.png'])
    @icons_url.append(['Home workout', 'lunges.png'])
    @icons_url.append(['Individual sports', 'sport.png'])
    @icons_url.append(['Team sports', 'sports.png'])
    @icons_url.append(%w[Stretching stretching.png])
    @icons_url.append(%w[Swimming swimmer.png])
    @icons_url.append(%w[Treadmill treadmill.png])
    @icons_url.append(%w[Cardio triangle.png])
    @icons_url.append(%w[Yoga yoga.png])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def groups_image_url(group)
    group.icon.nil? ? 'groups/noicon.png' : "groups/#{group.icon}"
  end

  def groups_image_url_show
    @group.icon.nil? ? 'groups/noicon.png' : "groups/#{@group.icon}"
  end

  def activity_icon_url_in_group_show
    @group.icon.nil? ? 'groups/noicon.png' : "groups/#{@group.icon}"
  end
end

app/views/groups/_icons.html.erb
<%= f.select :icon, @icons_url %>


<div class="images_wrapper d-inline-flex flex-wrap border border-primary rounded my-2">
<% @icons_url.each_with_index { |photo, i| %>
  <%  next if i == 0 %>
  <div class="col-wrapper col-2">
        <div class="card m-2 align-items-center" style="width: 80%;">
          <%=  image_tag('groups/' + photo[1], class: 'card-img-top mt-1', alt: photo[0], style: 'width: 4rem;')  %>
          <div class="card-body">
            <p class="card-text text-break" style="font-size:0.85rem;"><%=  photo[0]  %></p>
          </div>
        </div>
  </div>
  <%  } %>
</div>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'layouts/new_edit_form', model: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1 class="group-index-title text-center mt-2 mb-4">Groups listing</h1>

<table class="w-100">

  <tbody class="groups-listing-table w-100">

  <% @groups.each do |group| %>
    <tr class="<%= 'justify-content-around table_row' %>">
      <td class="image">
        <%= image_tag(groups_image_url(group), class: 'group_avatar img-thumbnail mx-3', alt: 'Group icon') %>
      </td>

      <td class="description ps-3 me-2">
        <h2><%= group.name %></h2>
        <h3><%= group.created_at.strftime("%b %d, %H:%M, %Y") %></h3>
      </td>
      <td class="actions">
        <ul>
          <li class="group-options my-1 me-1 text-center"><%= link_to 'Show', group %></li>
          <li class="group-options my-1 me-1 text-center"><%= link_to 'Edit', edit_group_path(group) %></li>
          <li class="group-options my-1 me-1 text-center"> <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %> </li>
        </ul>
      </td>

    </tr>

  <% end %>
  </tbody>
</table>

<div class="add-group-wrapper d-flex justify-content-around mt-5">
  <%= link_to new_group_path, class: 'edit-profile-text text-decoration-none text-center' do %>
    <div class="add-group-wrapper d-block">
      <i class="material-icons">add_circle_outline</i>
      <p>New group</p>
    </div>
  <% end %>


  <%= link_to user_path(session[:user_id]), class: 'edit-profile-text text-decoration-none text-center' do %>
    <div class="add-group-wrapper d-block">
      <i class="material-icons">reply</i>
      <p>Back</p>
    </div>
  <% end %>

</div>

app/views/groups/new.html.erb
<h1 class="mb-4">Create a group</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'layouts/new_edit_form', model: @group, icons: @icons_url %>
      </div>

    </div>
  </div>
</div>

app/views/groups/show.html.erb
<span></span>
<div class="group-title d-block container-fluid mt-4 text-center">
  <%= image_tag( groups_image_url_show, class: 'group_avatar img-thumbnail me-2', alt: 'Group avatar') %>
  <h1 class="group-name"><%= @group.name %></h1>
</div>

<div class="group-subtitle my-3 ms-3">Group transactions</div>
<div class="total-minutes container-fluid d-flex justify-content-between mb-4">
  <div>Total minutes: &nbsp;</div>
  <div><%= @group.activities.sum(:amount).round(2) %>&nbsp;mins.</div>
</div>




<table class="w-100">

  <tbody class="groups-listing-table w-100">

  <% @activities.each do |activity| %>

    <tr class="<%= 'justify-content-around  table_row' %>">
      <td class="image py-3">
        <%= image_tag(activity_icon_url_in_group_show, class: 'group_avatar img-thumbnail mx-3', alt: 'Group icon') %>
      </td>
      <td class="description me-2">
        <h2><%= activity.name %></h2>
        <h3><%= activity.created_at.strftime("%b %d, %H:%M, %Y") %></h3>
      </td>
      <td class="me-2">
        <h2 class="amount"><%= activity.amount.to_s %>&nbsp; mins.</h2>
      </td>
    </tr>
    <tr class="<%= 'justify-content-center  table_row' %>">
      <td class="author-cell"> Author:  <%= activity.author.username %></td>
    </tr>
  <% end %>
  </tbody>
</table>



<%= link_to groups_path, class: 'edit-profile-text text-decoration-none text-center' do %>
  <div class="add-group-wrapper d-block">
    <i class="material-icons">reply</i>
    <p>Back</p>
  </div>
<% end %>