config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :groups, only: [:new, :create, :edit, :update, :show, :destroy, :index]
  resources :activities, only: [:new, :create, :edit, :update, :show, :destroy, :index]
  resources :scoreboards, only: [:index]
  root 'sessions#login'



  #routes to handle sessions:
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :groups, class_name: 'Group', foreign_key: 'creator_id'
  has_many :activities, class_name: 'Activity', foreign_key: 'author_id'
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  def ungrouped_activities_from_user(current_user_id)
    Activity.includes(:author).where(group_id: nil).where(author_id: current_user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @icons_url = create_icons_array
  end

  def edit
    @user = User.find(params[:id])
    @icons_url = create_icons_array
  end

  def create
    @icons_url = create_icons_array
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:danger] = 'Invalid signup details'
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    @icons_url = create_icons_array
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        puts 'true in the if'
        format.html { redirect_to user_path(@user), notice: 'User details were successfully updated.' }
      else
        flash.now[:danger] = 'Invalid signup details'
        format.html { render :'users/edit', status: :unprocessable_entity }
      end
    end
  end

  def show
    redirect_to root_path unless session[:user_id]
    @user = User.find(session[:user_id]) if session[:user_id]
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :icon)
  end

  def create_icons_array
    @icons_url = []
    @icons_url.append(['Choose an avatar', 'nousericon.png'])
    @icons_url.append(['Anonymous', 'nousericon.png'])
    @icons_url.append(['Business man anonymous', 'businessman.png'])
    @icons_url.append(['Business man young', 'businessyoungman.png'])
    @icons_url.append(['Business man', 'businessmanface.png'])
    @icons_url.append(['Father', 'father.png'])
    @icons_url.append(['Girl', 'girl.png'])
    @icons_url.append(['Man', 'man.png'])
    @icons_url.append(['Ninja', 'ninja.png'])
    @icons_url.append(['Red head woman', 'redheadwoman.png'])
    @icons_url.append(['Woman', 'woman.png'])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def icon_url_for_user
    @user.icon.nil? ? 'users-avatars/nousericon.png' : "users-avatars/#{@user.icon}"
  end
end

app/views/users/_userform.html.erb
<section class="py-3 text-center container">
  <div class="row py-lg-3">
    <div class="col-12 mx-auto">


      <div class="border border-success rounded">

        <%= form_for @user do |f| %>
          <div class="container-fluid">
            <div class="row justify-content-center">
              <div class="d-flex justify-content-around my-1 w-75">
                <%= f.label :username, :class => 'sign-up-subtitle' %> <%= f.text_field :username, :class => 'border border-success ms-2 w-40' %>
              </div>
              <div class="d-flex justify-content-around my-1 w-75">
                <%= f.label :password, :class => 'sign-up-subtitle' %> <%= f.password_field :password, :class => 'border border-success ms-2 w-40' %>
              </div>
            </div>
          </div>

          <%= render 'layouts/icons', icons_url: @icons_url, f: f %>


          <div class="add-group-wrapper d-flex justify-content-around mt-5">

            <%= f.button :type => "submit", style: 'border-style: none; background-color: transparent;' do %>
              <div class="add-group-wrapper d-block">
                <i class="material-icons">save_alt</i>
              </div>
            <% end %>

            <%= link_to root_path, class: 'edit-profile-text text-decoration-none text-center' do %>
              <div class="add-group-wrapper d-block">
                <i class="material-icons">reply</i>
                <p>Back</p>
              </div>
            <% end %>

          </div>

      <% end %>
      </div>

      <div>

      </div>

    </div>
  </div>
</section>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'users/userform' %>

<%= link_to 'Back', @user, class: 'btn btn-success my-2 w-25 mb-5' %>

app/views/users/new.html.erb
<% @user.errors.full_messages.each do |message| %>
  <div class="alert alert-danger alert-dismissible fade show"> <%= message %> </div>
<%end%>

<h2 class="sign-up-title text-center">Sign up</h2>

<%= render 'users/userform'%>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="user-logo-info text-center mt-4">
        <%= image_tag(icon_url_for_user, class: 'img-thumbnail', alt: 'User avatar') %>
        <div class="user-name text-center"><%= @user.username.capitalize %></div>

        <%= link_to edit_user_path, class: 'edit-profile-text text-decoration-none text-center' do %>
            <i class="material-icons">settings</i>
        <% end %>


      </div>
    </div>
  </div>
</div>


<div class='user-menu-options mb-5'>
  <div><i class="main-screen-icons material-icons me-3">directions_run</i>
      <%= link_to 'All my activities', activities_path, class: '' %>
  </div>
  <div><i class="main-screen-icons material-icons me-3">directions_walk</i>
      <%= link_to 'All my external activities', activities_path(ungrouped: true) , class: 'text-decoration-none' %>
  </div>
  <div><i class="main-screen-icons material-icons me-3">groups</i>
      <%= link_to 'All groups', groups_path, class: 'text-decoration-none' %>
  </div>
  <div><i class="main-screen-icons material-icons me-3">assignment</i>
    <%= link_to 'Scoreboard', scoreboards_path, class: 'text-decoration-none' %>
  </div>
</div>

<%= link_to logout_path, class: 'edit-profile-text  text-decoration-none text-center' do %>
  <div class="add-group-wrapper d-block">
    <i class="material-icons logout-button">close</i>
    <p>Logout</p>
  </div>
<% end %>