config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :groups, only: [:new, :create, :edit, :update, :show, :destroy, :index]
  resources :activities, only: [:new, :create, :edit, :update, :show, :destroy, :index]
  resources :scoreboards, only: [:index]
  root 'sessions#login'



  #routes to handle sessions:
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :group, optional: true
  has_and_belongs_to_many :groups
  default_scope -> { order(created_at: :desc) }
  scope :ascending, -> { order(name: :asc) }

  validates :name, presence: true
  validates :amount, presence: true, numericality: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    current_user = User.find(session[:user_id])

    @activities = if params[:ungrouped]
                    current_user.ungrouped_activities_from_user(current_user.id)
                  else
                    current_user.activities.all
                  end
    puts 'hello'
  end

  def new
    @activity = Activity.new
    @groups = Group.all
    @groups_array = create_groups_array
    @activities_created = activities_created
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.author_id = session[:user_id]
    if @activity.save
      redirect_to @activity
    else
      flash[:danger] = 'Invalid activity details'
      redirect_to new_activity_path
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @groups = @activity.group.nil? ? nil : @activity.group
  end

  # GET /activity/1/edit
  def edit
    @activity = Activity.find(params[:id])
    @groups = Group.all
    @groups_array = create_groups_array
    @activities_created = activities_created
  end

  # PATCH/PUT /activities/1
  def update
    activity = Activity.find(params[:id])
    respond_to do |format|
      if activity.update(activity_params)
        format.html { redirect_to activity, notice: 'Activity details were successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  def destroy
    activity = Activity.find(params[:id])
    activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully deleted from database.' }
    end
  end

  private

  def activities_created
    Activity.ascending.pluck(:name)
  end

  def activity_params
    params.require(:activity).permit(:name, :amount, :group_id)
  end

  def create_groups_array
    arr = Group.all.pluck(:name, :id)
    arr.insert(0, ['No group', nil])
  end

  def create_icons_array
    @icons_url = []
    @icons_url.append(['Choose an avatar', 'noicon.png'])
    @icons_url.append(%w[Anonymous noicon.png])
    @icons_url.append(['Basket ball', 'basketball-ball.png'])
    @icons_url.append(%w[Cycling bicycle.png])
    @icons_url.append(%w[Weightlifting dumbbell.png])
    @icons_url.append(%w[Skating figure-skating.png])
    @icons_url.append(%w[Fitness fitness.png])
    @icons_url.append(%w[Jogging jogging.png])
    @icons_url.append(['Martial arts', 'kimono.png'])
    @icons_url.append(['Home workout', 'lunges.png'])
    @icons_url.append(['Individual sports', 'sport.png'])
    @icons_url.append(['Team sports', 'sports.png'])
    @icons_url.append(%w[Stretching stretching.png])
    @icons_url.append(%w[Swimming swimmer.png])
    @icons_url.append(%w[Treadmill treadmill.png])
    @icons_url.append(%w[Cardio triangle.png])
    @icons_url.append(%w[Yoga yoga.png])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def activities_title
    @activity_form_title = if params[:ungrouped]
                             'External activities listing'
                           else
                             'Activities listing'
                           end
  end

  def icon_url_for_activity_show
    @groups.nil? ? 'groups/noicon.png' : "groups/#{@groups.icon}"
  end

  def icon_url_for_activity_index(activity)
    activity.group.nil? || activity.group.icon.nil? ? 'groups/noicon.png' : "groups/#{activity.group.icon}"
  end

  def group_icon_div_text
    @groups.nil? ? 'No group' : @groups.name
  end

  def load_text_or_select(form)
    if params[:add_activity] || action_name == 'edit'
      render 'activities/textlabel_for_names', f: form
    else
      render 'activities/select_with_names', f: form
    end
  end

  def load_new_activity_icon
    render 'activities/load_new_activity_icon' if params[:add_activity].nil? && action_name != 'edit'
  end
end

app/views/activities/_activityform.html.erb
<div class="border border-success rounded">

  <%= form_for @activity, class: 'form-class' do |f| %>
    <div class="container-fluid">
      <div class="row justify-content-between">
        <div class="d-flex justify-content-between my-1">

          <%= load_text_or_select(f) %>
          <%= load_new_activity_icon %>


        </div>


        <div class="d-flex justify-content-between my-2 w-75">
          <%= f.label :amount %> <%= f.number_field :amount, in: -10000.0..10000.0, step: 0.01, :class => 'border border-success ms-2 w-40' %>
        </div>
        <div class="d-flex justify-content-around my-1 w-75">
          <% f.label :group_id %>
          <% f.text_field :group_id, :value => "158", :class => 'border border-success ms-2 w-40' %>
        </div>

        <%= render 'groups-listing', icons_url: @icons_url, f: f %>

      </div>
    </div>

    <div class="add-group-wrapper d-flex justify-content-around mt-5">

      <%= f.button :type => "submit", style: 'border-style: none; background-color: transparent;' do %>
        <div class="add-group-wrapper d-block">
          <i class="material-icons">save_alt</i>
        </div>
      <% end %>


      <%= link_to activities_path, class: 'edit-profile-text text-decoration-none text-center' do %>
        <div class="add-group-wrapper d-block">
          <i class="material-icons">reply</i>
          <p>Back</p>
        </div>
      <% end %>

    </div>


  <% end %>
</div>

app/views/activities/_groups-listing.html.erb
<%= f.select :group_id, @groups_array %>



<div class="images_wrapper d-inline-flex flex-wrap border border-primary rounded my-2 col-12">
  <% @groups.each_with_index { |group, i| %>

    <div class="col-wrapper col-3 col-md-2">
      <div class="avatar-image-card card m-1 align-items-center w-80">
        <%=  image_tag( 'groups/' + group.icon, class: 'avatar-image card-img-top mt-1', alt: 'Group icon')  %>
        <div class="card-body">
          <p class="avatar-image-text card-text text-break" ><%=  group.name  %></p>
        </div>
      </div>
    </div>
  <%  } %>
</div>

app/views/activities/_load_new_activity_icon.html.erb
  <%= link_to new_activity_url(add_activity: true) do %>
    <div class="add-group-wrapper d-block text-center">
      <i class="material-icons">add_circle_outline</i>
      <p>Add a new name</p>
    </div>
  <% end %>

app/views/activities/_select_with_names.html.erb
 <div class="d-block text-center">
    <div class="mb-3 choose-name">Choose a name</div>
    <div class="">
      <%= f.select :name, @activities_created %>
    </div>
  </div>

app/views/activities/_textlabel_for_names.html.erb
  <%= f.label :name %> <%= f.text_field :name, :class => 'border border-success ms-2 w-40' %>

app/views/activities/edit.html.erb
<h1 class="mb-4">Edit activity</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'activities/activityform', model: @activity, icons: @icons_url, groups_array: @groups_array %>
      </div>
      <div class="panel-footer">
        <p><%= link_to 'All activities', activities_path,  class: 'text-decoration-none text-muted' %></p>
      </div>
    </div>
  </div>
</div>

app/views/activities/index.html.erb
<h1 class="group-index-title text-center mt-2 mb-4"><%= activities_title %></h1>

<div class="total-minutes container-fluid d-flex justify-content-between mb-4">
  <div>Total minutes: &nbsp;</div>
  <div><%= @activities.sum(:amount).round(2) %>&nbsp;mins.</div>
</div>

<table class="w-100 mb-5">

  <tbody class="groups-listing-table w-100">

  <% @activities.each do |activity| %>
    <tr class="<%= 'justify-content-around  table_row' %>">
      <td class="image text-center">
        <%= image_tag(icon_url_for_activity_index(activity), class: 'activity-group_avatar img-thumbnail my-2', alt: 'Group icon') %>
      </td>

      <td class="description me-2">
        <div class="container-fluid d-flex justify-content-between align-content-center">
          <div class="activity-name-date">
            <h2><%= activity.name %></h2>
            <h3><%= activity.created_at.strftime("%b %d, %H:%M, %Y") %></h3>
          </div>
          <div class="activity-amount align-self-center">
            <div class="activity-amount-text"><%= activity.amount %></div>
            <div>&nbsp; mins.</div>
          </div>
        </div>
      </td>
      <td class="actions">
        <ul>
          <li class="group-options my-1 text-center"><%= link_to 'Show', activity %></li>
          <li class="group-options my-1 text-center"><%= link_to 'Edit', edit_activity_path(activity) %></li>
          <li class="group-options my-1 text-center"> <%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %> </li>
        </ul>
      </td>
    </tr>

  <% end %>
  </tbody>

</table>


<div class="add-group-wrapper d-flex justify-content-around mt-5">
  <%= link_to new_activity_path, class: 'edit-profile-text text-decoration-none text-center' do %>
    <div class="add-group-wrapper d-block">
      <i class="material-icons">add_circle_outline</i>
      <p>New activity</p>
    </div>
  <% end %>

  <%= link_to user_path(session[:user_id]), class: 'edit-profile-text text-decoration-none text-center' do %>
    <div class="add-group-wrapper d-block">
      <i class="material-icons">reply</i>
      <p>Back</p>
    </div>
  <% end %>

</div>

app/views/activities/new.html.erb
<h1 class="mb-4">Create an activity</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'activities/activityform', model: @activity, icons: @icons_url, groups_array: @groups_array, add_activity: params[:add_activity]%>
      </div>

    </div>
  </div>
</div>

app/views/activities/show.html.erb
<div class="container-fluid">
<h1 class="mt-4">Activity name: &nbsp; </h1>
  <div class="d-flex justify-content-around mt-3">
    <div class="d-block text-center">
      <%= image_tag(icon_url_for_activity_show, class: 'activity-group-avatar img-thumbnail', alt: 'Group icon') %>
      <h2 class="mb-5 mt-3 activity-group-name"><%=  group_icon_div_text %></h2>
    </div>
    <h2 class="mb-5 mt-3 activity-name"><%= @activity.name %></h2>

  </div>
<div>


  <div class="activity-subtitle">This activitity was created by: &nbsp; </div>
<div class="activity-info-text"><%= @activity.author.username %></div>
</div>

  <div class="mt-3">
<div class="activity-subtitle">Minutes exercising: &nbsp; </div>
<div class="activity-info-text"><%= @activity.amount %></div>
  </div>
  <div class="mt-3">
    <div class="activity-subtitle">Date of creation: &nbsp; </div>
    <div class="activity-info-text"><%= @activity.created_at.strftime("%B %d, %Y") %></div>
  </div>

<div class="add-group-wrapper d-flex justify-content-around mt-5">

  <%= link_to activities_path, class: 'edit-profile-text text-decoration-none text-center' do %>
    <div class="add-group-wrapper d-block">
      <i class="material-icons">reply</i>
      <p>Back</p>
    </div>
  <% end %>

</div>
</div>