config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :groups, only: [:new, :create, :edit, :update, :show, :destroy, :index]
  resources :activities, only: [:new, :create, :edit, :update, :show, :destroy, :index]
  resources :scoreboards, only: [:index]
  root 'sessions#login'



  #routes to handle sessions:
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
end

app/views/layouts/_header.html.erb
<div class="collapse" id="navbarToggleExternalContent">
  <div class="navbar-content-wrapper p-4">
    <h5 class="text-white h4">Menu</h5>
    <span class="text-muted">

        <ul class="list-group-horizontal-md list-group">
          <li><%= link_to 'Home', root_path,  class: 'navbar-links list-group-item text-decoration-none text-white' %></li>
          <%= navbar_links %>
        </ul>
      </span>
  </div>
</div>
<nav class="navbar navbar-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

app/views/layouts/_icons.html.erb
<%= f.select :icon, @icons_url %>



<div class="images_wrapper d-inline-flex flex-wrap border border-primary rounded my-2 col-12">
<% @icons_url.each_with_index { |photo, i| %>

  <%  next if i == 0 %>


  <div class="col-wrapper col-3 col-md-2">
        <div class="avatar-image-card card m-1 align-items-center w-80">
          <%=  image_tag( controller_name + photo[1], class: 'avatar-image card-img-top mt-1', alt: photo[0])  %>
          <div class="card-body">
            <p class="avatar-image-text card-text text-break" ><%=  photo[0]  %></p>
          </div>
        </div>
  </div>
  <%  } %>
</div>

app/views/layouts/_logged_in_user_links.html.erb
<li class="list-group-item navbar-links ms-md-1">
    <%= link_to 'Logout', logout_path,  class: 'text-decoration-none text-light' %></li>
<li class="list-group-item navbar-links ms-md-1">
    <%= link_to 'All my activities', activities_path,  class: 'text-decoration-none text-light' %></li>
<li class="list-group-item navbar-links ms-md-1">
    <%= link_to 'All my external activities', activities_path(ungrouped: true),  class: 'text-decoration-none text-light' %></li>
<li class="list-group-item navbar-links ms-md-1">
    <%= link_to 'All groups', groups_path,  class: 'text-decoration-none text-light' %></li>

app/views/layouts/_logged_out_user_links.html.erb
<li class="list-group-item navbar-links ms-md-1">
    <%= link_to 'Sign up', new_user_path, class: 'text-decoration-none text-white' %></li>

app/views/layouts/_new_edit_form.html.erb
<%= form_with(model: model, class: 'form-class') do |f| %>

  <% if model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this instance from being saved:</h2>

      <ul>
        <% model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name, class: 'name form-control mb-4', autofocus: true %>
  </div>



  <%= render 'layouts/icons', icons_url: @icons_url, f: f %>


  <div class="add-group-wrapper d-flex justify-content-around mt-5">

    <%= f.button :type => "submit", style: 'border-style: none; background-color: transparent;' do %>
      <div class="add-group-wrapper d-block">
        <i class="material-icons">save_alt</i>
      </div>
    <% end %>

    <%= link_to groups_path, class: 'edit-profile-text text-decoration-none text-center' do %>
      <div class="add-group-wrapper d-block">
        <i class="material-icons">reply</i>
        <p>Back</p>
      </div>
    <% end %>

  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RorCapstone</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Tangerine">
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


</head>

<body class="">


<%= render 'layouts/header' %>
<div class="">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">
      <%= content_tag(:div, message) %>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>